spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
      
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: task
        ddl-auto: update
        format_sql: true
        show-sql: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS=25

server:
  address: ${APP_ADDRESS}
  port: ${APP_PORT}
  compression:
    enabled: true
  error:
    include-message: always
  shutdown: "graceful"

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR
  file:
    name: logs/todo.log