spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  address: ${APP_ADDRESS}
  port: ${APP_PORT}
  compression:
    enabled: true
  error:
    include-message: always
  shutdown: "graceful"

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR
  file:
    name: logs/todo.log